"""RAG response generator.

Takes the user's query and the retrieved context chunks, formats them into a
strict prompt, and calls the LLM to generate an answer.

Prompt Engineering:
  The prompt is designed to minimize hallucination by explicitly instructing
  the model to only use the provided context and to say "I don't know" if the
  answer isn't there.
"""

from __future__ import annotations

from langchain_core.messages import HumanMessage, SystemMessage
from typing import Generator

from src.ml.llm import get_llm
from src.services.rag.models import Chunk
from src.utils.logger import get_logger

logger = get_logger(__name__)

# ── Prompt Templates ───────────────────────────────────────────────────────────

_SYSTEM_PROMPT = """You are RAGent, a highly precise and professional AI assistant.
Your task is to answer the user's question based strictly and ONLY on the provided context.

Rules:
1. You must ONLY use information found in the CONTEXT below.
2. You are allowed to use semantic reasoning (e.g. recognizing that "Project Lead" means "Project Manager").
3. If the CONTEXT does not contain the answer at all, you must say: "I cannot answer this based on the provided documents." Do not guess or use outside knowledge.
4. Be concise, direct, and factual.
5. Do not mention that you are reading from a context block. Just provide the answer.

Here are some known facts about the user that you may use to personalize your response if relevant:
{user_facts}
"""

_HUMAN_PROMPT_TEMPLATE = """CONTEXT:
{context}

USER QUESTION:
{question}
"""


# ── Generator ──────────────────────────────────────────────────────────────────

def generate_answer(query: str, context_chunks: list[Chunk], user_facts: list[str] | None = None) -> str:
    """Generate an answer to a query using the provided context chunks.

    Args:
        query:          The user's original question.
        context_chunks: The chunks retrieved from the vector DB.
        user_facts:     Optional list of long-term facts about the user.

    Returns:
        The text response generated by the LLM.
    """
    if not context_chunks:
        # Fast path: if no context was found, don't even bother calling the LLM
        logger.info("No context chunks provided to generator — skipping LLM call")
        return "I cannot answer this based on the provided documents (no relevant context found)."

    # Format the chunks into a single text block
    # We include the source and page number in the context so the LLM can
    # potentially reference them (we'll extract citations formally in Phase 2).
    formatted_context_parts = []
    for i, chunk in enumerate(context_chunks, start=1):
        formatted_context_parts.append(
            f"--- Document {i} (Source: {chunk.source}, Page: {chunk.page}) ---\n"
            f"{chunk.text}"
        )
    
    context_text = "\n\n".join(formatted_context_parts)

    human_prompt = _HUMAN_PROMPT_TEMPLATE.format(
        context=context_text,
        question=query,
    )

    logger.debug(
        "Calling LLM",
        extra={
            "query": query,
            "context_chunks_count": len(context_chunks),
            "context_length": len(context_text),
        },
    )

    facts_str = "\n".join(f"- {f}" for f in user_facts) if user_facts else "None provided."
    system_prompt = _SYSTEM_PROMPT.format(user_facts=facts_str)

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=human_prompt),
    ]

    try:
        llm = get_llm()
        response = llm.invoke(messages)
        
        # response.content can sometimes be a list of blocks, but for text models it's usually a string
        answer = str(response.content)
        
        logger.info("LLM generation complete", extra={"answer_length": len(answer)})
        return answer

    except Exception as exc:
        logger.error(
            "LLM generation failed",
            extra={"error": str(exc), "query": query},
            exc_info=True,
        )
        return "An error occurred while generating the response. Please check the logs."


def stream_answer(query: str, context_chunks: list[Chunk], user_facts: list[str] | None = None) -> Generator[str, None, None]:
    """Stream an answer to a query using the provided context chunks.

    Args:
        query:          The user's original question.
        context_chunks: The chunks retrieved from the vector DB.
        user_facts:     Optional list of long-term facts about the user.

    Yields:
        Chunks of text generated by the LLM.
    """
    if not context_chunks:
        logger.info("No context chunks provided to generator — skipping LLM stream")
        yield "I cannot answer this based on the provided documents (no relevant context found)."
        return

    formatted_context_parts = []
    for i, chunk in enumerate(context_chunks, start=1):
        formatted_context_parts.append(
            f"--- Document {i} (Source: {chunk.source}, Page: {chunk.page}) ---\n"
            f"{chunk.text}"
        )
    
    context_text = "\n\n".join(formatted_context_parts)

    human_prompt = _HUMAN_PROMPT_TEMPLATE.format(
        context=context_text,
        question=query,
    )

    logger.debug(
        "Starting LLM stream",
        extra={
            "query": query,
            "context_chunks_count": len(context_chunks),
            "context_length": len(context_text),
        },
    )

    facts_str = "\n".join(f"- {f}" for f in user_facts) if user_facts else "None provided."
    system_prompt = _SYSTEM_PROMPT.format(user_facts=facts_str)

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=human_prompt),
    ]

    try:
        llm = get_llm()
        for chunk in llm.stream(messages):
            content = chunk.content
            if content:
                yield str(content)

    except Exception as exc:
        logger.error(
            "LLM stream failed",
            extra={"error": str(exc), "query": query},
            exc_info=True,
        )
        yield "An error occurred while generating the response. Please check the logs."
