"""Groundedness Scorer.

Calculates how strongly the generated answer is supported by the retrieved context.
It embeds both the answer and the individual chunks, and returns a cosine similarity score.
"""

import math

from src.ml.embedding import embed
from src.services.rag.models import Chunk
from src.utils.logger import get_logger

logger = get_logger(__name__)


def cosine_similarity(vec1: list[float], vec2: list[float]) -> float:
    """Calculate the cosine similarity between two vectors."""
    dot_product = sum(a * b for a, b in zip(vec1, vec2))
    norm_a = math.sqrt(sum(a * a for a in vec1))
    norm_b = math.sqrt(sum(b * b for b in vec2))
    
    if norm_a == 0 or norm_b == 0:
        return 0.0
        
    return dot_product / (norm_a * norm_b)


def calculate_groundedness(answer: str, chunks: list[Chunk]) -> tuple[float, list[float]]:
    """Calculate how well the answer is grounded in the chunks.
    
    Args:
        answer: The text generated by the LLM.
        chunks: The list of chunks retrieved from the vector DB.
        
    Returns:
        A tuple of (overall_confidence, list_of_chunk_scores)
    """
    if not chunks:
        return 0.0, []
        
    # If the LLM successfully admitted it didn't know, we consider this highly grounded
    # in the *absence* of information, rather than hallucinated.
    if "cannot answer this" in answer.lower() or "don't have any ingested documents" in answer.lower():
        return 1.0, [0.0] * len(chunks)
        
    # Embed the generated answer
    answer_vector = embed([answer])[0]
    
    # Re-embed the chunks (fast because they are cached or small)
    chunk_texts = [c.text for c in chunks]
    chunk_vectors = embed(chunk_texts)
    
    scores = []
    for chunk_vec in chunk_vectors:
        score = cosine_similarity(answer_vector, chunk_vec)
        scores.append(score)
        
    # The overall confidence is the maximum similarity. If the answer perfectly matches
    # at least one chunk's semantic meaning, it's considered grounded.
    overall_confidence = max(scores) if scores else 0.0
    
    logger.debug(
        "Groundedness calculated",
        extra={
            "overall_confidence": overall_confidence,
            "chunk_scores": scores
        }
    )
    
    return overall_confidence, scores
