"""Groundedness Scorer (LLM-as-a-Judge).

Uses an LLM to evaluate how strongly the generated answer is supported by the retrieved context.
This prevents false positives where mathematically dissimilar but factually correct short answers 
are flagged as hallucinations.
"""

from pydantic import BaseModel, Field
from langsmith import traceable

from src.ml.llm import get_llm
from src.services.rag.models import Chunk
from src.utils.logger import get_logger

logger = get_logger(__name__)


class GroundednessResult(BaseModel):
    """The structured output for the groundedness judge."""
    is_grounded: bool = Field(
        ..., 
        description="True if the answer is fully supported by the provided context. False if it contains hallucinated facts or outside knowledge."
    )
    confidence_score: float = Field(
        ..., 
        description="A score from 0.0 to 1.0 indicating how confident you are in your judgment.",
        ge=0.0,
        le=1.0
    )


@traceable(name="ragas_faithfulness_judge")
def calculate_groundedness(answer: str, chunks: list[Chunk]) -> float:
    """Calculate how well the answer is grounded in the chunks using an LLM.
    
    Args:
        answer: The text generated by the LLM.
        chunks: The list of chunks retrieved from the vector DB.
        
    Returns:
        The confidence score (0.0 to 1.0).
    """
    if not chunks:
        return 0.0
        
    # If the LLM successfully admitted it didn't know, we consider this highly grounded
    # in the *absence* of information, rather than hallucinated.
    if "cannot answer this" in answer.lower() or "don't have any ingested documents" in answer.lower():
        return 1.0
        
    try:
        llm = get_llm()
        judge = llm.with_structured_output(GroundednessResult)
        
        # Combine the chunks into a single readable context
        context_text = "\n\n".join(f"--- Document {i} ---\n{c.text}" for i, c in enumerate(chunks, 1))
        
        system_prompt = (
            "You are an expert hallucination detector (a Faithfulness Judge).\n"
            "Your task is to determine if the provided ANSWER is completely supported by the provided CONTEXT.\n"
            "If the ANSWER contains ANY facts, names, or numbers not found in the CONTEXT, it is a hallucination (is_grounded=False).\n"
            "If the ANSWER is a short, direct extraction from the CONTEXT (e.g. just a name), it is fully grounded (is_grounded=True).\n"
            "Do not penalize the answer for being concise."
        )
        
        human_prompt = f"CONTEXT:\n{context_text}\n\nANSWER:\n{answer}"
        
        messages = [
            ("system", system_prompt),
            ("human", human_prompt)
        ]
        
        result: GroundednessResult = judge.invoke(messages)
        
        # If the judge says it's grounded, return the high confidence score.
        # If it says it's not, force the score to 0.0 to trigger the fallback guardrail.
        final_score = result.confidence_score if result.is_grounded else 0.0
        
        logger.debug(
            "Groundedness judged",
            extra={
                "is_grounded": result.is_grounded,
                "judge_confidence": result.confidence_score,
                "final_score": final_score
            }
        )
        
        return final_score
        
    except Exception as e:
        logger.warning(
            "Groundedness judge failed, defaulting to low confidence",
            extra={"error": str(e)}
        )
        return 0.0
